## 🧠 `ai-workflows/README.md`

```md
# Vyrade AI Workflows Library

This repository hosts structured workflows generated by Vyrade's AI engine, built with LangGraph, RAG pipelines, and tool binding. Each workflow includes a Markdown explanation and an optional JSON output.

## 📂 Structure

/workflows/ → `.md` + `.json` files for each workflow  
/meta/ → Metadata like leaderboard, tags  
/templates/ → Workflow submission templates

## 🔧 Example Workflow
- Title: Lead Qualification Email Automation  
- Tools: Clay, GPT-4o, Instantly  
- Files: `lead-qualification-email.md`, `lead-qualification-email.json`

## 🧩 Contribute
1. Fork the repo
2. Copy `/templates/workflow-template.md`
3. Submit a PR

## 📜 License
MIT
